### ISSUE TITLE
Error whenever someone joins

### ISSUE THREAD

**Issue by gidskie** [BlockHorizons/PerWorldPlayer#7]
Notice: Undefined offset: 0 in phar:///home/container/plugins/PerWorldPlayer (3).phar/src/BlockHorizons/PerWorldPlayer/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 119
Fatal error: Uncaught TypeError: Argument 2 passed to BlockHorizons\PerWorldPlayer\libs\poggit\libasynql\result\SqlColumnInfo::__construct() must be of the type string, null given, called in phar:///home/container/plugins/PerWorldPlayer (3).phar/src/BlockHorizons/PerWorldPlayer/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 119 and defined in phar:///home/container/plugins/PerWorldPlayer (3).phar/src/BlockHorizons/PerWorldPlayer/libs/poggit/libasynql/result/SqlColumnInfo.php:37
Stack trace:
#0 phar:///home/container/plugins/PerWorldPlayer (3).phar/src/BlockHorizons/PerWorldPlayer/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php(119): BlockHorizons\PerWorldPlayer\libs\poggit\libasynql\result\SqlColumnInfo->__construct('armor_inventory', NULL)
#1 phar:///home/container/plugins/PerWorldPlayer (3).phar/src/BlockHorizons/PerWorldPlayer/libs/poggit/libasynql/base/SqlSlaveThread.php(77): BlockHorizons\PerWorldPlayer\libs\poggit\libasynql\sqlite3\Sqlite3Thread->executeQuery(Object(SQLite3), 3, 'SELECT HEX(armo...', Array) in phar:///home/container/plugins/PerWorldPlayer (3).phar/src/BlockHorizons/PerWorldPlayer/libs/poggit/libasynql/result/SqlColumnInfo.php on line 37

Players cannot also break or place blocks even OPs

**Comment by gidskie** [comment]
thank you for fixing it🤩
